version: '3.9'

services:
  backend:
    container_name: backend
    image: my-application/backend:1.0
    build:
      context: ./myapp-back
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - java_db

  java_db:
    container_name: java_db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    container_name: frontend
    image: my-application/frontend:1.0
    build:
      context: ./myapp-front
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always

volumes:
  pgdata: {}