version: '3.9'

services:
  backend:
    container_name: backend
    image: my-application/backend:1.0
    build:
      context: ./myapp-back
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - SPRING_POSTGRES_URL=jdbc:postgresql://java_db:5432/mydbtest
      - SPRING_POSTGRES_USERNAME=myapplication
      - SPRING_POSTGRES_PASSWORD=M3P@ssw0rd!
    depends_on:
      - java_db

  java_db:
    container_name: java_db
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: myapplication
      POSTGRES_PASSWORD: M3P@ssw0rd!
      POSTGRES_DB: mydbtest
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    container_name: frontend
    image: my-application/frontend:1.0
    build:
      context: ./myapp-front
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always

volumes:
  pgdata: {}