apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: {{ .Values.backend.image }} # TO DO check values.yaml
        ports:
        - containerPort: {{ .Values.backend.servicePort }} # 8080
        env:
        - name: SPRING_POSTGRES_USERNAME
          value: myapplication
        - name: SPRING_POSTGRES_PASSWORD
          value: AVNS_y5nmiqI6aGbqjLOCFe3
        - name: SPRING_POSTGRES_URL
          value: jdbc:postgresql://pg-694830e-yy-7535.a.aivencloud.com:21195/mydbtest # TO ADD 
          # jdbc:postgresql://[Host]:[Port]/[DatabaseName]