name: Docker Image CI

on:
  push:
    branches: [ "feat/dockerfiles" ]
  pull_request:
    branches: [ "feat/dockerfiles" ]

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push backend
      uses: docker/build-push-action@v2
      with:
        context: ./myapp-back
        file: ./myapp-back/Dockerfile
        push: true
        tags: yylkhalidi/my-application-backend:1.0

  build-and-push-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push backend
      uses: docker/build-push-action@v2
      with:
        context: ./myapp-back
        file: ./myapp-back/Dockerfile
        push: true
        tags: yylkhalidi/my-application-backend:1.0

    - name: Build and push frontend
      uses: docker/build-push-action@v2
      with:
        context: ./myapp-front
        file: ./myapp-front/Dockerfile
        push: true
        tags: yylkhalidi/my-application-frontend:1.0
